# Generated by Django 4.0.6 on 2022-07-17 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_giver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
